// <auto-generated />
using System;
using HealthcareManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthcareManagement.Persistence.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    [Migration("20251101082631_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "Filan Fisteku"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "Dem Alia"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "Ali Dema"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "Sadik Sadiku"
                        });
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("DoctorSpecializations");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 3,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 3,
                            SpecializationId = 8
                        },
                        new
                        {
                            DoctorId = 4,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 4,
                            SpecializationId = 6
                        });
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "Cardiology",
                            Tags = "heart,chest pain,cardio,cardiac,blood pressure,hypertension,arrhythmia,chest discomfort"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "Dermatology",
                            Tags = "skin,rash,acne,eczema,psoriasis,dermatitis,itchy,redness,lesion,mole"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "Neurology",
                            Tags = "headache,seizure,neuro,neurological,migraine,epilepsy,stroke,brain,memory,dizziness"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "General Medicine",
                            Tags = "cough,fever,flu,cold,general,common,infection,virus,bacterial,symptoms"
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Name = "Internal Medicine",
                            Tags = "internal,organ,digestive,stomach,abdomen,chronic,diabetes,hypertension,metabolic"
                        },
                        new
                        {
                            Id = 6,
                            Deleted = false,
                            Name = "Pediatrics",
                            Tags = "child,children,pediatric,baby,infant,toddler,kid,childhood,adolescent"
                        },
                        new
                        {
                            Id = 7,
                            Deleted = false,
                            Name = "Orthopedics",
                            Tags = "bone,joint,fracture,broken,sprain,orthopedic,back pain,knee,shoulder,spine"
                        },
                        new
                        {
                            Id = 8,
                            Deleted = false,
                            Name = "Emergency Medicine",
                            Tags = "emergency,urgent,acute,trauma,injury,accident,severe,critical,emergency care"
                        });
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Appointment", b =>
                {
                    b.HasOne("HealthcareManagement.Domain.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareManagement.Domain.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.DoctorSpecialization", b =>
                {
                    b.HasOne("HealthcareManagement.Domain.Models.Doctor", "Doctor")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareManagement.Domain.Models.Specialization", "Specialization")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSpecializations");
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HealthcareManagement.Domain.Models.Specialization", b =>
                {
                    b.Navigation("DoctorSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
